### ISSUE TITLE
upower code

### ISSUE THREAD

**Issue by Israel-** [zdobersek/UPower-Battery-Status-API#2]
Hi, I was wondering if I could use your code to make a GTK battery monitor
It is a very nice example!

**Comment by zdobersek** [comment]
Sure, go ahead.

**Comment by Israel-** [comment]
Awesome!!  What license can I use?  is GPL3 ok, or do you prefer a specific kind of license?

**Comment by zdobersek** [comment]
GPLv3 is OK.

**Comment by Israel-** [comment]
Thank you!! I will host it here soon!!
